substitutions:
  name: apollo-plt-1
  version: "24.10.22.1"
  device_description: ${name} made by Apollo Automation - version ${version}.

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

api:
  services:
    - service: play_buzzer
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'
  reboot_timeout: 0s

globals:
  - id: cycleCounter
    type: int
    restore_value: no
    initial_value: '0'
  - id: button_press_timestamp
    restore_value: no
    type: uint32_t
    initial_value: '0'


captive_portal:

web_server:
  port: 80


one_wire:
  - platform: gpio
    pin: GPIO5

output:
  - platform: ledc
    pin: GPIO10
    id: buzzer
rtttl:
 output: buzzer

number:
  - platform: template
    name: Air Temperature Offset
    id: aht_temperature_offset
    restore_value: true
    initial_value: 0.0
    min_value: -70.0
    max_value: 70.0
    entity_category: "CONFIG"
    unit_of_measurement: "°C"
    optimistic: true
    update_interval: never
    step: 0.1
    mode: box

  - platform: template
    name: Air Humidity Offset
    id: aht_humidity_offset
    restore_value: true
    initial_value: 0
    min_value: -70.0
    max_value: 70.0
    entity_category: "CONFIG"
    unit_of_measurement: "%"
    optimistic: true
    update_interval: never
    step: 0.1
    mode: box
  - platform: template
    id: wet_voltage
    name: 100% Water Voltage
    initial_value: '1.5'
    optimistic: true
    update_interval: never
    step: 0.1
    mode: box
    restore_value: true
    entity_category: "CONFIG"
    min_value: 0.0
    max_value: 5.0
  - platform: template
    id: dry_voltage
    name: Dry Voltage
    initial_value: '2.7'
    restore_value: true
    entity_category: "CONFIG"
    optimistic: true
    update_interval: never
    step: 0.1
    mode: box
    min_value: 0.0
    max_value: 5.0

binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected

sensor:
  - platform: internal_temperature
    name: "ESP Temperature"
    id: sys_esp_temperature

  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s

  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"


light:
  - platform: esp32_rmt_led_strip
    id: rgb_light
    name: "RGB Light"
    pin: GPIO3
    rmt_channel: 0
    default_transition_length: 0s
    chipset: WS2812
    num_leds: 1
    rgb_order: grb
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 1000ms
          update_interval: 1000ms
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"

  - platform: factory_reset
    disabled_by_default: True
    name: "Factory Reset ESP"
    id: factory_reset_all

switch:
  - platform: factory_reset
    id: factory_reset_switch
    internal: true



